services:
  postgres:
    image: postgres:17
    container_name: booking_postgres
    restart: always
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: